swears = [
    'Kys', 'Fuck you', 'Your mom giey', 'Ligma balls',
    'Γαμώ τη μάνα σου', 'Γαμώ τον πατέρα σου',
    'كس أمك', 'يا حيوان يا خرا كل تيز أمك', 'تيز أمك'
    ]

yo_mama_jokes = [
    "Yo mama's so fat, when she fell I didn't laugh, but the sidewalk cracked up.",
    "Yo mama's so fat, when she skips a meal, the stock market drops.",
    "Yo mama's so fat, it took me two buses and a train to get to her good side.",
    "Yo mama's so fat, when she goes camping, the bears hide their food.",
    "Yo mama's so fat, if she buys a fur coat, a whole species will become extinct.",
    "Yo mama's so fat, she stepped on a scale and it said: 'To be continued.'",
    "Yo mama's so fat, I swerved to miss her in my car and ran out of gas.",
    "Yo mama's so fat, when she wears high heels, she strikes oil.",
    "Yo mama's so fat, she was overthrown by a small militia group, and now she's known as the Republic of Yo Mama.",
    "Yo mama's so fat, when she sits around the house, she SITS AROUND the house.",
    "Yo mama's so fat, her car has stretch marks.",
    "Yo mama's so fat, she can't even jump to a conclusion.",
    "Yo mama's so fat, her blood type is Ragù.",
    "Yo mama's so fat, if she was a Star Wars character, her name would be Admiral Snackbar.",
    "Yo mama's so fat, she brought a spoon to the Super Bowl.",
    "Yo mama's so stupid, she stared at a cup of orange juice for 12 hours because it said 'concentrate.'",
    "Yo mama's so stupid when they said it was chilly outside, she grabbed a bowl.",
    "Yo mama's so stupid, she put lipstick on her forehead to make up her mind.",
    "Yo mama's so stupid, when they said, 'Order in the court,' she asked for fries and a shake.",
    "Yo mama's so stupid, she thought a quarterback was a refund.",
    "Yo mama's so stupid, she got hit by a parked car.",
    "Yo mama's so stupid, when I told her that she lost her mind, she went looking for it",
    "Yo mama's so stupid when thieves broke into her house and stole the TV, she chased after them shouting 'Wait, you forgot the remote!'",
    "Yo mama's so stupid, she went to the dentist to get a Bluetooth.",
    "Yo mama's so stupid, she took a ruler to bed to see how long she slept.",
    "Yo mama's so stupid, she got locked in the grocery store and starved to death.",
    "Yo mama's so stupid, when I said, 'Drinks on the house,' she got a ladder.",
    "Yo mama's so stupid, it takes her two hours to watch 60 Minutes.",
    "Yo mama's so stupid, she put airbags on her computer in case it crashed.",
    "Yo mama's so ugly, she threw a boomerang and it refused to come back.",
    "Yo mama's so old, her social security number is one.",
    "Yo mama's so ugly, she made a blind kid cry.",
    "Yo mama's so ugly, her portraits hang themselves.",
    "Yo mama's so old, she walked out of a museum and the alarm went off.",
    "Yo mama's teeth are so yellow when she smiles at traffic, it slows down.",
    "Yo mama's armpits are so hairy, it looks like she's got Buckwheat in a headlock.",
    "Yo mama's so ugly, when she was little, she had to trick-or-treat by phone.",
    "Yo mama's so ugly, her birth certificate is an apology letter.",
    "Yo mama's so ugly, she looked out the window and was arrested for mooning.",
    "Yo mama's so poor, the ducks throw bread at her.",
    "Yo mama's so poor, she chases the garbage truck with a grocery list.",
    "Yo mama's cooking so nasty, the flies got together and fixed the hole in the window screen.",
    "Yo mama's so depressing, blues singers come to visit her when they've got writer's block.",
    "Yo mama's so short, you can see her feet on her driver's license.",
    "Yo mama's so poor, she can't even afford to pay attention.",
    "Yo mama so big, her belt size is 'equator.'",
    "Yo mama's so classless, she's a Marxist utopia.",
    "Yo mama so short, she went to see Santa and he told her to get back to work.",
    "Yo mama so scary, the government moved Halloween to her birthday.",
    "Yo mama's so nasty, they used to call them jumpolines 'til yo mama bounced on one.",
    "Yo mama's teeth so yellow, I can't believe it's not butter.",
    "Yo mama's so poor, Nigerian princes wire her money.",
    "Yo mama so dumb, she went to the eye doctor to get an iPhone.",
    "Yo mama's so lazy, she stuck her nose out the window and let the wind blow it."
    ]

puns = [
    "What does a cloud wear under his raincoat?\nThunderwear.",
    "What do kids play when they can’t play with a phone?\nBored games.",
    "What do you call two monkeys sharing an Amazon account?\nPRIME-mates.",
    "What do birds give out on Halloween?\nTweets.",
    "Why was the weightlifter upset?\nShe worked with dumbbells.",
    "Why are teddy bears never hungry?\nThey’re always stuffed!",
    "What did the policeman say to his tummy?\n“Freeze. You’re under a vest.”",
    "What does one volcano say to the other?\n“I lava you!”",
    "What’s Thanos’ favorite app to talk to friends?\nSnapchat.",
    "What event do spiders love to attend?\nWebbings.",
    "What did one math book say to the other?\n“I’ve got so many problems.”",
    "Why do ducks have tail feathers?\nTo cover their buttquacks.",
    "Why can’t you ever tell a joke around glass?\nIt could crack up.",
    "How do you know when a bike is thinking?\nYou can see its wheels turning.",
    "How did the baby tell her mom she had a wet diaper?\nShe sent her a pee-mail.",
    "How did Benjamin Franklin feel when he discovered electricity?\nShocked!",
    "Why did the Daddy rabbit go to the barber?\nHe had a lot of little hares.",
    "What kind of shoes do private investigators wear?\nSneak-ers.",
    "How do billboards talk?\nSign language.",
    "What do you call it when your nose is stuffy at the rodeo?\nCowboy Boogie.",
    "What game does the sky love to play?\nTwister.",
    "Why do we never tell jokes about pizza?\nThey’re too cheesy.",
    "What kind of lunch do moms never prepare in the morning?\nTheir own.",
    "Did you hear the joke about the roof?\nNever mind, it’s over your head.",
    "What time is it when people are throwing pieces of bread at your head?\nTime to duck.",
    "What do you do if someone rolls their eyes at you?\nRoll them back.",
    "What’s the difference between a guitar and a fish?\nYou can tune a guitar but you can’t tuna fish.",
    "What did the sink say to the potty?\n“You look flushed!”",
    "What’s a snake’s strongest subject in school?\nHiss-tory.",
    "Why did the God of Thunder need to stretch his muscles so much as a kid?\nHe was a little Thor.",
    "What kind of music do mummies listen to?\nWrap music.",
    "What kind of nut doesn’t like money?\nCash ew.",
    "Learning how to collect trash wasn’t hard.\nI just picked it up as I went along.",
    "Why is it so windy inside a stadium?\nThere are hundreds of fans.",
    "Do you know how many famous men and women were born on your birthday?\nNone, only babies.",
    "Why didn’t the lamp sink?\nIt was too light.",
    "Why do vampires seem sick?\nThey’re always coffin.",
    "Where do cows go on Dec. 31st?\nA moo year’s eve party.",
    "Why shouldn’t you tell secrets in a cornfield?\nThere are too many ears.",
    "Where do you find a dog with no legs?\nRight where you left him!",
    "What did the snowman ask the other snowman?\nDo you smell carrots?",
    "How do you stop an astronaut’s baby from crying?\nYou rocket.",
    "What did the fisherman say to the magician?\n“Pick a cod, any cod.”",
    "Why did the cookie go to the doctor’s office?\nHe was feeling crummy.",
    "What do Olympic sprinters eat before a race?\nNothing. They fast.",
    "Why do bowling pins have such a hard life?\nThey’re always getting knocked down.",
    "Why did the golfer wear two pairs of pants?\nJust in case he got a hole in one.",
    "Where were pencils invented?\nPENCIL-vania.",
    "Why are penguins socially awkward?\nBecause they can’t break the ice.",
    "How much does a pirate pay for corn?\nA BUCK-aneer.",
    "Why can’t you trust zookeepers?\nThey love cheetahs.",
    "Where do you learn to make ice cream?\nSundae school.",
    "Why did the tomato blush?\nBecause it saw the salad dressing.",
    "Why couldn’t the duck pay for dinner?\nHer bill was too big.",
    "What kind of tree fits in your hand?\nA palm tree.",
    "What did Jack say to Jill after they rolled down the hill?\n“I think I spilled the water.”",
    "Why are ghosts such bad liars?\nYou can see right through them.",
    "What animal dresses up and howls?\nA wearwolf.",
    "What’s red and bad for your teeth?\nA brick.",
    "What did the mother elephant say to her kids when they weren’t behaving?\n“Tusk, tusk.”",
    "What are bald sea captains most worried about?\nCap sizes.",
    "What do you call a retired vegetable?\nA has-bean.",
    "What gets wetter the more it dries?\nA towel.",
    "Where do hamburgers go dancing?\nA meatball.",
    "What’s blue and smells like red paint?\nBlue paint.",
    "How do elves learn how to spell?\nThey study the elf-abet.",
    "Why were bikes suspended from school?\nThey spoke too much.",
    "What kind of music do balloons hate?\nPop.",
    "What time is it when a ball goes through the window?\nTime to get a new window.",
    "Why can’t your hand be 12 inches long?\nBecause then it would be a foot.",
    "If you take your watch to be fixed, make sure you don’t pay upfront.\nWait until the time is right.",
    "What do you call a bear with no teeth?\nA gummy bear.",
    "What did the traffic light say to the car?\n“Don’t look. I’m about to change.”",
    "What did one DNA strand ask the other DNA strand?\n“Do these genes look OK?”",
    "Did you hear about the two guys who stole a calendar?\nThey each got six months.",
    "What do you call a sad strawberry?\nA blueberry.",
    "What do you call a cow with no legs?\nGround beef!",
    "Why can’t you hear a pterodactyl going to the bathroom?\nBecause the “P” is silent.",
    "What’s a skeleton’s favorite instrument?\nA trom-bone.",
    "Why can’t you give Elsa a balloon?\nShe’ll “Let It Go.”",
    "Don’t leave any food around your computer.\nIt takes a lot of bytes.",
    "Why did the dinosaur cross the road?\nThe chicken didn’t exist yet.",
    "What’s a king’s favorite kind of weather?\nReign.",
    "What did the broccoli say to the celery?\n“Quit stalking me.”",
    "Why can’t Cinderella play soccer?\nBecause she’s always running away from the ball.",
    "What happened with the kidnapping situation in the park?\nThey woke him up.",
    "Why can’t the music teacher start his car?\nHis keys are on the piano.",
    "What did Aquaman say to his kids when they wouldn’t eat their food?\n“Water you waiting for?”",
    "Why do you never see elephants hiding in trees?\nBecause they are really good at it.",
    "How does Darth Vader like his toast?\nOn the dark side.",
    "What do Alexander the Great and Winnie the Pooh have in common?\nThe same middle name.",
    "What do cows read?\nCATTLE-logs.",
    "Why are spiders great web developers?\nThey like finding bugs.",
    "What do you call a fly without wings?\nA walk!",
    "Why kind of bug is in the FBI?\nA SPY-der.",
    "Can a kangaroo jump higher than the Empire State Building?\nOf course! The Empire State Building can’t jump!",
    "I spent five minutes fixing a broken clock yesterday.\nAt least, I think it was five minutes…",
    "Why are elephants so wrinkled?\nBecause they take too long to iron!",
    "How did the barber win the race?\nHe knew a shortcut.",
    "What do you call a cow that can’t moo?\nA milk dud.",
    "What did one hat say to the other?\n“Stay here, I’m going on ahead.”",
    "What’s the best thing to put into a pie?\nYour teeth.",
    "What’s green, has six legs, and if it drops out of a tree onto you will kill you?\nA pool table.",
    "What room doesn’t have doors?\nA mushroom.",
    "How do modern-day pirates keep in touch?\nSEA-mail.",
    "Why did the scarecrow get a promotion?\nHe was outstanding in his field.",
    "Where does Superman’s wife drive?\nLois’ lane.",
    "Where do horses live?\nIn neighhh-borhoods.",
    "What do you get when you put cheese next to some ducks?\nCheese and quackers.",
    "What do you call a tired pea?\nSleep-pea.",
    "What do cats eat for breakfast?\nMice krispies.",
    "Why was SpongeBob always praying?\nHe’s so hole-y.",
    "Why do computers never fall asleep?\nThey’re too wired.",
    "Why did the Scottish man have plumbing issues?\nHe only had bagpipes.",
    "Why did the florist give so many kisses?\nShe had two-lips.",
    "What happens in a cave in the rainforest?\nAmazon Echo.",
    "Did you hear the story about the claustrophobic astronaut?\nHe just needed some space.",
    "What did the buffalo say when his son left?\n“Bison!”",
    "I used to be addicted to the hokey pokey…\nBut then I turned myself around.",
    "Why should you never trust stairs?\nThey’re always up to something.",
    "Have you heard the rumor about butter?\nNever mind, I shouldn’t be spreading it.",
    "Why did the actor fall through the floorboards?\nHe was just going through a stage.",
    "Why don’t scientists trust atoms?\nBecause they make up everything.",
    "How do you keep a bagel from getting away?\nPut lox on it.",
    "What do you call a parade of rabbits hopping backward?\nA receding hare-line.",
    "What does Charles Dickens keep in his spice rack?\nThe best of thymes, the worst of thymes.",
    "What did the shark say when he ate the clownfish?\n“This tastes a little funny.”",
    "Why did the yogurt go to the art exhibition?\nBecause it was cultured.",
    "Why is it annoying to eat next to basketball players?\nThey dribble all the time.",
    "How do you throw a space party?\nYou planet.",
    "What’s the most expensive kind of fish?\nA gold fish.",
    "How did the cake grow a daisy?\nIt was made with flower.",
    "What’s scarier than a monster?\nA momster.",
    "Why did the garden feel overcrowded?\nThere wasn’t mushroom.",
    "What is brown and sticky?\nA stick!",
    "What did one block say to the other when he was ready to leave the party?\n“LEGO.”",
    "Why did the little lamb go everywhere Mary went?\nHe wanted to mark his territory.",
    "What did the guitar say to the lead singer of the band?\n“Stop stringing me along.”",
    "What do you call a student who doesn’t like math class?\nCalcu-hater.",
    "What do piggies use when they have an infection?\nAntibiotic oinkment.",
    "Why is a flock of geese like Wikipedia?\nThey’re flying in-formation.", 
    "Why is it OK if you forget how to make a boomerang on Instagram?\nIt will come back to you.",
    "What’s Superman’s favorite drink?\nPUNCH.",
    "What does Minnie Mouse drive?\nA Minnie van!",
    "What did one elevator yell to the other?\nI’m falling!", 
    "Which hand is better to paint with?\nNeither! A paint brush is better.",
    "What do you call cheese that doesn’t belong to you?\nNacho cheese!",
    "Why does the moon say she doesn’t want to eat?\n“She’s full.”",
    "What goes up but doesn’t come back down?\nYour age.",
    "Where do fish keep their money?\nIn the riverbank.",
    "Knock, knock.\nWho’s there?\nAnnie.\nAnnie Who?\nAnnie thing you can do, I can do better.",
    "Knock, knock.\nWho’s there?\nVoodoo.\nVoodoo who?\nVoodoo you think you are?",
    "Who gives sharks presents on Christmas?\nSanta Jaws.",
    "What always comes at the beginning of a parade?\nThe letter “P.”",
    "What did the baby corn say to the mama corn?\n“Where’s popcorn?”",
    "Why don’t we eat clowns at Hanukkah?\nBecause they taste funny.",
    "Who delivers Christmas presents to dogs?\nSanta Paws.",
    "What happened after the shark got famous?\nHe became a starfish.",
    "Why was the cookie sad?\nBecause his mom was a wafer so long.",
    "How does a cucumber become a pickle?\nIt goes through a jarring experience.",
    "Why do bananas have to put on sunscreen before they go to the beach?\nBecause they might peel!",
    "What did the egg say to another egg?\n“Have an eggselent day!”",
    "What do knights do when they are scared of the dark?\nThey turn on the knight light!",
    "Why do seagulls fly over the sea?\nBecause if they flew over the bay, they would be bagels.",
    "What do you call a boomerang that doesn’t come back?\nA stick.",
    "What can smell without a noise?\nA fart.",
    "What did the beach say to the tide when it came in?\n“Long time, no sea.”",
    "What did the duck say to the comedian?\n“You quack me up.”",
    "Why did the girl smear peanut butter on the road?\nTo go with the traffic jam!",
    "What do you call a hen who counts her eggs?\nA mathemachicken.",
    "What do you call a fake noodle?\nAn impasta.",
    "What time do ducks wake up?\nAt the quack of dawn.",
    "Why did the banana go to the doctor?\nIt wasn’t peeling well.",
    "Why did the man get hit by a bike every day?\nHe was stuck in a vicious cycle.",
    "What did the tomato say to the other tomato during a race?\n“Ketchup.”",
    "Why do fish live in salt water?\nBecause pepper makes them sneeze!",
    "What do you call a pig that does karate?\nA pork chop.",
    "When do you go in red and stop on green?\nWhen you are eating a watermelon.",
    "What do you think of that new restaurant on the moon?\nThe food is great, but there’s not much atmosphere.",
    "Why do melons have weddings?\nBecause they cantaloupe.",
    "What do you do when you see a spaceman?\nPark your car, man.",
    "What do cats wear to bed?\nPaw-jamas.",
    "What did the hungry dalmatian say when he had some kibble?\n“That hit the spot!”",
    "What did the dog say to the sandpaper?\n“Ruff!”",
    "What do you call a dog in the winter?\nA chili dog!",
    "Where should a dog never go shopping?\nA flea market.",
    "What is the dog’s favorite button on a remote?\nPaws.",
    "What happens when it rains cats and dogs?\nYou can step into a poodle.",
    "What kind of dog does Dracula have?\nA bloodhound!",
    "What is a dog’s favorite city?\nNew Yorkie!",
    "What’s a cat’s favorite color?\nPurrrrr-ple.",
    "Why are cats so good at video games?\nBecause they have nine lives.", 
    "Why is a leopard so bad at hiding?\nBecause he’s always spotted.",
    "What’s a cat’s favorite song?\nThree Blind Mice.",
    "What state has a lot of dogs and cats?\nPets-sylvania.",
    "Why did the ghost go into the bar?\nFor the Boos.",
    "Why did the ghost starch his sheet?\nHe wanted everyone to be scared stiff.",
    "What do you say when you catch a ghost?\n“Gotchu Boo!”",
    "Where do ghosts buy their food?\nAt the ghost-ery store!",
    "What’s the ghost’s favorite thing about Thanksgiving dinner?\nThe grave-y.", 
    "If athletes get athlete’s foot, then what do astronauts get?\nMissle-toe.",
    "Who in the solar system has the most loose change?\nThe moon. It keeps changing quarters.",
    "How much is the moon worth?\nOne dollar, because it has four quarters.",
    "What should you do when you see a green alien?\nWait until it’s ripe!",
    "Why did Mickey Mouse go to space?\nTo find Pluto.",
    "How do you know when the moon has enough to eat?\nWhen it’s full.",
    "What did one shooting star say to the other?\n“Pleased to meteor.”",
    "What did the Martians wear to Mother’s Day dinner?\nSpace suits.",
    "What did Venus say to Saturn?\n“Give me a ring sometime!”",
    "What do planets like to read?\nComet books!",
    "What do you call a dinosaur that is sleeping?\nA dino-snore.",
    "What is fast, loud, and crunchy?\nA rocket chip!",
    "What did the left eye say to the right eye?\n“Between us, something smells.”",
    "What do you get when you cross a vampire and a snowman?\nFrostbite!",
    "What did one plate say to the other plate?\n“Dinner is on me.”",
    "Why did the student eat his homework?\nThe teacher told him it was a piece of cake.",
    "What is brown, hairy, and wears sunnies?\nA coconut on vacation.",
    "Two pickles fell on the floor. What did one say to the other?\n“Dill with it.”",
    "Why did the kid cross the playground?\nTo get to the other slide.",
    "How does a vampire start a letter?\nTomb it may concern…",
    "What do you call a droid that takes the long way around?\nR2 detour.",
    "How do all the oceans say hello to each other?\n“They wave!”",
    "What did one wall say to the other wall?\n“I’ll meet you at the corner!”",
    "Knock, knock.\nWho’s there?\nCows go.\nCows go who?\nNo, cows go MOO!",
    "What do you call a cow with two legs?\nLean meat!",
    "Knock knock.\nWho’s there?\nA little old lady?\nA little old lady who?\nI didn’t know you could yodel!",
    "Why do bees have sticky hair?\nBecause they use honeycombs!",
    "Why did the computer go to the dentist?\nIt had a blue tooth.",
    "How does a cow do math?\nWith a cow-culator.",
    "What do you get when you cross a turtle with a porcupine?\nA slowpoke.",
    "What do you call an alligator in a vest?\nAn investigator!",
    "Why did the toilet paper roll down the hill?\nTo get to the bottom.",
    "What is a witch’s favorite school subject?\nSpelling.",
    "Why is a bad joke like a pencil?\nBecause it has no point.",
    "What animal needs to wear a wig?\nA bald eagle.",
    "If April showers bring Mayflowers, what do Mayflowers bring?\nPilgrims!",
    "How do you keep an elephant from charging?\nTake away her credit card!",
    "What falls in the winter but never gets hurt?\nSnow.",
    "Why are frogs so happy?\nThey eat what bugs them.",
    "What do you get when a cow laughs?\nA milkshake.",
    "What goes tick-tock and woof-woof?\nA watchdog.",
    "Why did the girl throw a stick of butter?\nShe wanted to see a butter-fly!",
    "Which dinosaur had the best vocabulary?\nThe thesaurus.",
    "Why isn’t there a clock in the library?\nBecause it tocks too much.",
    "Why can’t pirates learn the alphabet?\nThey keep getting lost at C.",
    "What’s worse than finding a worm in your apple?\nFinding half a worm.",
    "What do you get when dinosaurs crash their cars?\nTyrannosaurus wrecks.",
    "What has four wheels and flies?\nA garbage truck.",
    "What kind of driver never gets a ticket?\nA screwdriver.",
    "What kind of money do mermaids use?\nSand dollars.",
    "How do you get a squirrel to like you?\nAct like a nut!",
    "Why do gorillas have big nostrils?\nBecause they have such big fingers to pick with!\n"
    ]